name: catch2 tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install Cmake
      run: brew install cmake
    - name: Clone Catch2 code
      run: git clone https://github.com/catchorg/Catch2.git
    - name: Build and Install Catch2
      run: cd Catch2
      run: ls -hal
      run: cmake -Bbuild -H. -DBUILD_TESTING=OFF
      run: sudo cmake --build build/ --target install
      run: cd ..
    - name: Build project using cmake
      run: ./cmake.sh
    - name: Build and Run Tests
      run: ./tests.sh
